export const ARIA_ATTRIBUTE_DESCRIPTIONS: Record<string, string> = {
  role: 'Defines the semantic role exposed to assistive technology.',
  'aria-controls': 'References the controlled element while the related content is mounted.',
  'aria-current': 'Marks the current item in a set or navigation trail.',
  'aria-describedby': 'References descriptive text associated with the control.',
  'aria-disabled': 'Indicates that the control is disabled.',
  'aria-expanded': 'Indicates whether the controlled content is expanded.',
  'aria-hidden': 'Hides decorative content from assistive technology.',
  'aria-invalid': 'Indicates that the field has a validation error.',
  'aria-label': 'Provides an accessible label when visible text is not sufficient.',
  'aria-labelledby': 'References the element that labels the control or region.',
  'aria-live': 'Announces dynamic status changes to assistive technology.',
  'aria-modal': 'Identifies modal content that traps interaction outside the dialog.',
  'aria-orientation': 'Communicates horizontal or vertical orientation.',
  'aria-readonly': 'Indicates that the control value cannot be changed by the user.',
  'aria-required': 'Indicates that user input is required.',
  'aria-selected': 'Indicates the currently selected option or tab.',
  'aria-valuemax': 'Defines the maximum value for range-like controls.',
  'aria-valuemin': 'Defines the minimum value for range-like controls.',
  'aria-valuenow': 'Defines the current numeric value for range-like controls.',
  'aria-valuetext': 'Provides human-readable text for the current value.',
}
export const DATA_ATTRIBUTE_DESCRIPTIONS: Record<string, string> = {
  'data-active': 'Present when the item is active.',
  'data-checked': 'Present when the item is checked or selected.',
  'data-current': 'Present when the item represents the current location.',
  'data-disabled': 'Present when the component or item is disabled.',
  'data-dragging': 'Present while the related thumb or handle is being dragged.',
  'data-highlighted': 'Present when the item is highlighted by pointer or keyboard navigation.',
  'data-invalid': 'Present when the field has a validation error.',
  'data-loading': 'Present when the component is loading.',
  'data-open': 'Present when the disclosure or overlay is open.',
  'data-orientation': 'Stores the rendered orientation.',
  'data-readonly': 'Present when the field is read-only.',
  'data-required': 'Present when the field is required.',
  'data-selected': 'Present when the item is selected.',
  'data-side': 'Stores the resolved floating content side.',
  'data-size': 'Stores the resolved size variant.',
  'data-slot': 'Identifies the rendered slot for styling hooks and selectors.',
  'data-state': 'Stores the component state used by styling hooks.',
  'data-status': 'Stores async loading, loaded, or error status.',
  'data-variant': 'Stores the resolved visual variant.',
}
